import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'ur';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Hero
    'hero.tagline': 'Empower Your Umrah Journeys: From Chaos to Clarity, One Pilgrim at a Time.',
    'hero.subtitle': 'Local-first PWA for agents—upload, validate, manage, and export pilgrim data securely offline.',
    'hero.cta': 'Get Started Free',
    'hero.ctaNote': 'No Data Leaves Your Device',
    'hero.signUp': 'Sign Up',
    'hero.logIn': 'Log In',
    
    // Navigation
    'nav.features': 'Features',
    'nav.blueprint': 'Blueprint',
    'nav.contact': 'Contact',
    
    // Blueprint Section
    'blueprint.title': 'Maximal Background Integration Blueprint',
    'blueprint.subtitle': 'Swap .env once, connect DB, and UmrahOps is ready—full pipelines from auth to exports.',
    
    // Pipeline titles
    'pipeline.env': 'Environment & Config Pipeline',
    'pipeline.env.desc': 'Centralized .env file loads all credentials for Supabase, OpenAI, and logging services. Single source of truth for seamless configuration.',
    
    'pipeline.auth': 'Authentication Pipeline',
    'pipeline.auth.desc': 'Supabase Auth integration with secure token management. .env provides VITE_SUPABASE_URL and ANON_KEY for instant setup.',
    
    'pipeline.csv': 'CSV Import & Cleaning Pipeline',
    'pipeline.csv.desc': 'Upload CSVs, normalize data into local SQLite, auto-detect duplicates and missing fields. DB layer handles all validation.',
    
    'pipeline.ai': 'AI/Predictive Pipeline',
    'pipeline.ai.desc': 'GPT-4o-mini powered risk scoring for travelers. OPENAI_API_KEY from .env enables intelligent conflict detection.',
    
    'pipeline.workflow': 'Workflow/Step Engine Pipeline',
    'pipeline.workflow.desc': 'State machine for pilgrim progress tracking. Local DB triggers UI updates and background syncs.',
    
    'pipeline.whatsapp': 'WhatsApp Messaging Pipeline',
    'pipeline.whatsapp.desc': 'One-click messaging with DB-tracked delivery status. Template management and batch sending capabilities.',
    
    'pipeline.pdf': 'PDF Export Pipeline',
    'pipeline.pdf.desc': 'Client-side PDF generation for paperwork. No server required—all exports happen locally.',
    
    'pipeline.audit': 'Audit & Logging Pipeline',
    'pipeline.audit.desc': 'Immutable audit logs in local SQLite with optional push to LOG_SERVER_URL for compliance.',
    
    'pipeline.sync': 'UI Refresh/Background Sync Pipeline',
    'pipeline.sync.desc': 'Real-time UI updates from DB changes. Service worker enables offline-first functionality.',
    
    'pipeline.dev': 'Developer-Friendly Notes Pipeline',
    'pipeline.dev.desc': 'Comprehensive documentation and migration scripts. Environment-based configuration for dev/staging/prod.',
    
    'pipeline.storage': 'Local Storage Pipeline',
    'pipeline.storage.desc': 'SQLite-powered local database with Prisma ORM. All sensitive data stays on-device for privacy.',
    
    // Features
    'features.title': 'Core Capabilities',
    'features.subtitle': 'Powered by centralized .env for seamless setup',
    
    'feature.validation.title': 'Smart Validation',
    'feature.validation.desc': 'Auto-detect overbookings and conflicts via DB validation. Catch errors before they become problems.',
    
    'feature.whatsapp.title': 'WhatsApp Integration',
    'feature.whatsapp.desc': 'One-click messaging with DB-tracked status. Keep pilgrims informed throughout their journey.',
    
    'feature.audit.title': 'Immutable Audits',
    'feature.audit.desc': 'Complete audit trails in local DB with optional remote push. Full compliance, zero data loss.',
    
    'feature.offline.title': 'Offline-First',
    'feature.offline.desc': 'All operations work without internet. .env-configured services sync when connectivity returns.',
    
    // Footer
    'footer.privacy': 'Privacy',
    'footer.contact': 'Contact',
    'footer.copyright': '© 2026 UmrahOps. All rights reserved.',
    'footer.tagline': 'Your data stays local. Your pilgrims stay organized.',
    
    // Auth
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.account': 'My Account',
    'auth.signOut': 'Sign Out',
    'auth.loginDescription': 'Enter your credentials to access your dashboard',
    'auth.signupDescription': 'Create an account to start managing your groups',
    
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.subtitle': 'Overview of all your assigned groups',
    'dashboard.searchPlaceholder': 'Search groups...',
    'dashboard.groupName': 'Group Name',
    'dashboard.date': 'Date',
    'dashboard.travelers': 'Travelers',
    'dashboard.booking': 'Booking',
    'dashboard.paperwork': 'Paperwork',
    'dashboard.messaging': 'Messaging',
    'dashboard.progress': 'Progress',
    'dashboard.open': 'Open',
    'dashboard.openGroup': 'Open Group',
    'dashboard.noGroups': 'No groups found',
    'dashboard.bookingsConfirmed': 'Bookings confirmed',
    'dashboard.paperworkComplete': 'Paperwork complete',
    'dashboard.messagesSent': 'Messages sent',
    'dashboard.risk': 'Risk',
    'dashboard.totalGroups': 'Total Groups',
    'dashboard.totalTravelers': 'Total Travelers',
    'dashboard.avgBooking': 'Avg Booking',
    'dashboard.avgPaperwork': 'Avg Paperwork',
    'dashboard.avgMessaging': 'Avg Messaging',
    'dashboard.refresh': 'Refresh',
    'dashboard.retry': 'Retry',
    'dashboard.sortBy': 'Sort by',
    'dashboard.sortDateDesc': 'Date (newest)',
    'dashboard.sortDateAsc': 'Date (oldest)',
    'dashboard.sortCompletion': 'Completion',
    'dashboard.sortRisk': 'Risk level',
    'dashboard.sortTravelers': 'Travelers count',
    'dashboard.filterBy': 'Filter',
    'dashboard.filterAll': 'All groups',
    'dashboard.filterComplete': 'Complete',
    'dashboard.filterInProgress': 'In progress',
    'dashboard.filterAtRisk': 'At risk',
    'dashboard.backToDashboard': 'Back to Dashboard',
    'dashboard.groupDetail': 'Group Detail',
    'dashboard.groupDetailPlaceholder': 'Full group management interface coming soon...',
    // Group Detail
    'group.tabTravelers': 'Travelers',
    'group.tabHotels': 'Hotels',
    'group.tabPaperwork': 'Paperwork',
    'group.tabMessaging': 'Messaging',
    'group.tabExport': 'Export',
    'group.name': 'Name',
    'group.passport': 'Passport',
    'group.actions': 'Actions',
    'group.selected': 'selected',
    'group.confirmBookings': 'Confirm Bookings',
    'group.riskReasons': 'Risk Reasons',
    'group.available': 'available',
    'group.hotelAssignment': 'Hotel Assignment',
    'group.selectHotel': 'Select Hotel',
    'group.left': 'left',
    'group.overbooking': 'Overbooking',
    'group.assigned': 'Assigned',
    'group.pending': 'Pending',
    'group.status': 'Status',
    'group.overallProgress': 'Overall Progress',
    'group.complete': 'Complete',
    'group.inProgress': 'In Progress',
    'group.incomplete': 'Incomplete',
    'group.filterByRisk': 'Filter by Risk',
    'group.highRisk': 'High Risk',
    'group.mediumRisk': 'Medium Risk',
    'group.lowRisk': 'Low Risk',
    'group.markAllComplete': 'Mark All Complete',
    'group.selectTemplate': 'Select Template',
    'group.messagesSummary': 'Messages Sent',
    'group.sent': 'Sent',
    'group.template': 'Template',
    'group.priority': 'Priority',
    'group.highPriority': 'High',
    'group.mediumPriority': 'Medium',
    'group.lowPriority': 'Low',
    'group.openWhatsApp': 'WhatsApp',
    'group.markSent': 'Mark Sent',
    'group.markFailed': 'Failed',
    'group.delivered': 'Delivered',
    'group.notSent': 'Not Sent',
    'group.failed': 'Failed',
    'group.exportOptions': 'Export Options',
    'group.includeTravelers': 'Include Travelers List',
    'group.includeHotels': 'Include Hotel Assignments',
    'group.includePaperwork': 'Include Paperwork Status',
    'group.includeMessaging': 'Include Messaging Summary',
    'group.includeAuditLog': 'Include Audit Log',
    'group.previewReport': 'Preview Report',
    'group.downloadReport': 'Download Report',
    'group.reportPreview': 'Report Preview',
    'group.clickPreview': 'Click "Preview Report" to see the report',
    'group.exportSuccess': 'Report downloaded successfully',
    'group.exportFailed': 'Failed to generate report',
    // Audit Log
    'audit.title': 'Audit Log',
    'audit.subtitle': 'Review all activity and change history',
    'audit.search': 'Search',
    'audit.searchPlaceholder': 'Search by action, resource, user...',
    'audit.actionType': 'Action Type',
    'audit.allActions': 'All Actions',
    'audit.dateFrom': 'From Date',
    'audit.dateTo': 'To Date',
    'audit.selectDate': 'Select date',
    'audit.clearFilters': 'Clear Filters',
    'audit.timestamp': 'Timestamp',
    'audit.agent': 'Agent',
    'audit.action': 'Action',
    'audit.target': 'Target',
    'audit.notes': 'Notes',
    'audit.noLogs': 'No audit logs found',
    'audit.showing': 'Showing',
    'audit.of': 'of',
    'audit.entries': 'entries',
    'audit.exportSuccess': 'Export successful',
    'audit.exportFailed': 'Export failed',
    'audit.logsExported': 'logs exported',
    // Settings
    'settings.title': 'Settings',
    'settings.subtitle': 'Manage your account and preferences',
    'settings.profile': 'Profile',
    'settings.profileDesc': 'Update your personal information',
    'settings.displayName': 'Display Name',
    'settings.displayNamePlaceholder': 'Your name',
    'settings.changePassword': 'Change Password',
    'settings.changePasswordDesc': 'Update your password for security',
    'settings.currentPassword': 'Current Password',
    'settings.newPassword': 'New Password',
    'settings.confirmPassword': 'Confirm Password',
    'settings.weak': 'Weak',
    'settings.fair': 'Fair',
    'settings.good': 'Good',
    'settings.strong': 'Strong',
    'settings.passwordsMatch': 'Passwords match',
    'settings.passwordsDontMatch': 'Passwords do not match',
    'settings.invalidEmail': 'Invalid email address',
    'settings.profileUpdated': 'Profile Updated',
    'settings.profileUpdatedDesc': 'Your profile has been updated successfully',
    'settings.passwordChanged': 'Password Changed',
    'settings.passwordChangedDesc': 'Your password has been updated successfully',
    'settings.passwordMismatch': 'New passwords do not match',
    'settings.passwordTooWeak': 'Password is too weak',
    'settings.error': 'Error',
    'settings.updateFailed': 'Failed to update',
    'settings.passwordChangeFailed': 'Failed to change password',
    'settings.logoutFailed': 'Failed to logout',
    'settings.saving': 'Saving...',
    'settings.saveChanges': 'Save Changes',
    'settings.updating': 'Updating...',
    'settings.updatePassword': 'Update Password',
    'settings.loggingOut': 'Logging out...',
    'settings.developerDebug': 'Developer Debug',
    'settings.environmentVars': 'Environment Variables',
    'settings.sessionInfo': 'Session Info',
    'settings.sessionStatus': 'Session Status',
    'settings.sessionExpired': 'Session expired',
    'settings.sessionActive': 'Active',
    'settings.minutesRemaining': 'minutes remaining',
    'settings.remaining': 'remaining',
    'settings.userId': 'User ID',
    // Toast notifications
    'toast.travelerUpdated': 'Traveler Updated',
    'toast.travelerUpdatedDesc': '{name} has been updated',
    'toast.travelerUpdatedDescGeneric': 'Traveler information updated',
    'toast.bookingConfirmed': 'Booking Confirmed',
    'toast.bookingConfirmedDesc': 'Traveler booking confirmed',
    'toast.bookingsConfirmedDesc': '{count} bookings confirmed',
    'toast.paperworkComplete': 'Paperwork Complete',
    'toast.paperworkCompleteDesc': '{name} paperwork marked complete',
    'toast.paperworkCompleteDescGeneric': 'Paperwork status updated',
    'toast.messageSent': 'Message Sent',
    'toast.messageSentDesc': 'Message sent to {name}',
    'toast.messageSentDescGeneric': 'Message status updated',
    'toast.groupStatusChanged': 'Group Status Changed',
    'toast.groupStatusChangedDesc': '{name} status updated',
    'toast.groupStatusChangedDescGeneric': 'Group status updated',
    'toast.csvImported': 'CSV Imported',
    'toast.csvImportedDesc': '{count} travelers imported successfully',
    'toast.csvImportedDescGeneric': 'Travelers imported successfully',
    'toast.exportComplete': 'Export Complete',
    'toast.exportCompleteDesc': 'Report downloaded successfully',
    'toast.error': 'Error',
    'toast.errorDesc': 'An error occurred',
    // CSV Upload
    'csv.title': 'Import Travelers',
    'csv.description': 'Upload a CSV file to add travelers to this group',
    'csv.dropHere': 'Drop your CSV file here',
    'csv.orClick': 'or click to browse files',
    'csv.downloadTemplate': 'Download Template',
    'csv.preview': 'Preview Import',
    'csv.previewDescription': 'Review the data before importing',
    'csv.valid': 'valid rows',
    'csv.invalid': 'invalid rows',
    'csv.status': 'Status',
    'csv.missingField': 'Missing required field: {field}',
    'csv.invalidPassport': 'Invalid passport format',
    'csv.invalidRowsWarning': '{count} rows have errors and will be skipped',
    'csv.cancel': 'Cancel',
    'csv.importing': 'Importing...',
    'csv.import': 'Import {count} Travelers',
    // Demo walkthrough
    'demo.watchDemo': 'Watch Demo',
    'demo.demo': 'Demo',
    'demo.step': 'Step',
    'demo.previous': 'Previous',
    'demo.next': 'Next',
    'demo.finish': 'Get Started',
    'demo.welcome': 'Welcome to UmrahOps',
    'demo.welcomeDesc': 'Let us show you how UmrahOps simplifies Umrah group management with our local-first, privacy-focused approach.',
    'demo.heroSection': 'Get Started Quickly',
    'demo.heroSectionDesc': 'Click "Get Started Free" to create your account. All your data stays on your device—no cloud required.',
    'demo.features': 'Core Capabilities',
    'demo.featuresDesc': 'UmrahOps provides smart validation, WhatsApp integration, immutable audits, and offline-first functionality.',
    'demo.validation': 'Smart Validation',
    'demo.validationDesc': 'Automatically detect overbookings, passport conflicts, and missing information before they become problems.',
    'demo.whatsapp': 'WhatsApp Integration',
    'demo.whatsappDesc': 'Send pre-built message templates to pilgrims with one click. Track delivery status in real-time.',
    'demo.blueprint': 'Integration Blueprint',
    'demo.blueprintDesc': 'Our plug-and-play architecture connects to your existing systems via a single .env configuration file.',
    'demo.pipelines': 'Powerful Pipelines',
    'demo.pipelinesDesc': 'From CSV import to PDF export, each pipeline is optimized for speed and reliability.',
    'demo.getStarted': 'Ready to Begin?',
    'demo.getStartedDesc': 'Create your free account and start managing your Umrah groups with confidence. No data leaves your device.',
  },
  ur: {
    // Hero
    'hero.tagline': 'اپنے عمرہ کے سفر کو بااختیار بنائیں: افراتفری سے وضاحت تک، ایک زائر ایک وقت میں۔',
    'hero.subtitle': 'ایجنٹس کے لیے لوکل فرسٹ PWA—اپ لوڈ کریں، توثیق کریں، زائرین کا ڈیٹا آف لائن محفوظ طریقے سے منظم کریں اور ایکسپورٹ کریں۔',
    'hero.cta': 'مفت شروع کریں',
    'hero.ctaNote': 'کوئی ڈیٹا آپ کے آلے سے باہر نہیں جاتا',
    'hero.signUp': 'سائن اپ',
    'hero.logIn': 'لاگ ان',
    
    // Navigation
    'nav.features': 'خصوصیات',
    'nav.blueprint': 'بلیو پرنٹ',
    'nav.contact': 'رابطہ',
    
    // Blueprint Section
    'blueprint.title': 'زیادہ سے زیادہ بیک گراؤنڈ انٹیگریشن بلیو پرنٹ',
    'blueprint.subtitle': 'ایک بار .env بدلیں، DB کنیکٹ کریں، اور UmrahOps تیار ہے—auth سے exports تک مکمل پائپ لائنز۔',
    
    // Pipeline titles
    'pipeline.env': 'ماحول اور کنفیگ پائپ لائن',
    'pipeline.env.desc': 'مرکزی .env فائل Supabase، OpenAI، اور لاگنگ سروسز کے لیے تمام اسناد لوڈ کرتی ہے۔ بے ہموار کنفیگریشن کے لیے واحد ذریعہ۔',
    
    'pipeline.auth': 'توثیق پائپ لائن',
    'pipeline.auth.desc': 'محفوظ ٹوکن مینجمنٹ کے ساتھ Supabase Auth انٹیگریشن۔ .env فوری سیٹ اپ کے لیے VITE_SUPABASE_URL اور ANON_KEY فراہم کرتا ہے۔',
    
    'pipeline.csv': 'CSV درآمد اور صفائی پائپ لائن',
    'pipeline.csv.desc': 'CSVs اپ لوڈ کریں، ڈیٹا کو مقامی SQLite میں نارملائز کریں، ڈپلیکیٹس اور گمشدہ فیلڈز کا خودکار پتہ لگائیں۔ DB لیئر تمام توثیق کو سنبھالتی ہے۔',
    
    'pipeline.ai': 'AI/پیش گوئی پائپ لائن',
    'pipeline.ai.desc': 'مسافروں کے لیے GPT-4o-mini سے چلنے والی رسک سکورنگ۔ .env سے OPENAI_API_KEY ذہین تنازعات کا پتہ لگانے کو فعال کرتی ہے۔',
    
    'pipeline.workflow': 'ورک فلو/سٹیپ انجن پائپ لائن',
    'pipeline.workflow.desc': 'زائرین کی پیش رفت کی ٹریکنگ کے لیے اسٹیٹ مشین۔ مقامی DB UI اپ ڈیٹس اور بیک گراؤنڈ سنکس کو ٹرگر کرتی ہے۔',
    
    'pipeline.whatsapp': 'واٹس ایپ میسجنگ پائپ لائن',
    'pipeline.whatsapp.desc': 'DB-ٹریکڈ ڈیلیوری اسٹیٹس کے ساتھ ایک کلک میسجنگ۔ ٹیمپلیٹ مینجمنٹ اور بیچ بھیجنے کی صلاحیتیں۔',
    
    'pipeline.pdf': 'PDF ایکسپورٹ پائپ لائن',
    'pipeline.pdf.desc': 'کاغذی کارروائی کے لیے کلائنٹ سائیڈ PDF جنریشن۔ کوئی سرور درکار نہیں—تمام ایکسپورٹس مقامی طور پر ہوتے ہیں۔',
    
    'pipeline.audit': 'آڈٹ اور لاگنگ پائپ لائن',
    'pipeline.audit.desc': 'تعمیل کے لیے LOG_SERVER_URL پر اختیاری پش کے ساتھ مقامی SQLite میں ناقابل تغیر آڈٹ لاگز۔',
    
    'pipeline.sync': 'UI ریفریش/بیک گراؤنڈ سنک پائپ لائن',
    'pipeline.sync.desc': 'DB تبدیلیوں سے ریئل ٹائم UI اپ ڈیٹس۔ سروس ورکر آف لائن فرسٹ فنکشنالٹی کو فعال کرتا ہے۔',
    
    'pipeline.dev': 'ڈیولپر دوستانہ نوٹس پائپ لائن',
    'pipeline.dev.desc': 'جامع دستاویزات اور مائیگریشن اسکرپٹس۔ dev/staging/prod کے لیے ماحول پر مبنی کنفیگریشن۔',
    
    'pipeline.storage': 'لوکل اسٹوریج پائپ لائن',
    'pipeline.storage.desc': 'Prisma ORM کے ساتھ SQLite سے چلنے والا مقامی ڈیٹا بیس۔ رازداری کے لیے تمام حساس ڈیٹا آلے پر رہتا ہے۔',
    
    // Features
    'features.title': 'بنیادی صلاحیتیں',
    'features.subtitle': 'بے ہموار سیٹ اپ کے لیے مرکزی .env سے تقویت یافتہ',
    
    'feature.validation.title': 'سمارٹ توثیق',
    'feature.validation.desc': 'DB توثیق کے ذریعے اوور بکنگز اور تنازعات کا خودکار پتہ لگائیں۔ غلطیوں کو مسائل بننے سے پہلے پکڑیں۔',
    
    'feature.whatsapp.title': 'واٹس ایپ انٹیگریشن',
    'feature.whatsapp.desc': 'DB-ٹریکڈ اسٹیٹس کے ساتھ ایک کلک میسجنگ۔ زائرین کو ان کے سفر میں باخبر رکھیں۔',
    
    'feature.audit.title': 'ناقابل تغیر آڈٹس',
    'feature.audit.desc': 'اختیاری ریموٹ پش کے ساتھ مقامی DB میں مکمل آڈٹ ٹریلز۔ مکمل تعمیل، صفر ڈیٹا نقصان۔',
    
    'feature.offline.title': 'آف لائن فرسٹ',
    'feature.offline.desc': 'تمام آپریشنز بغیر انٹرنیٹ کے کام کرتے ہیں۔ .env-کنفیگرڈ سروسز کنیکٹیویٹی واپس آنے پر سنک ہوتی ہیں۔',
    
    // Footer
    'footer.privacy': 'رازداری',
    'footer.contact': 'رابطہ',
    'footer.copyright': '© 2026 UmrahOps۔ جملہ حقوق محفوظ ہیں۔',
    'footer.tagline': 'آپ کا ڈیٹا مقامی رہتا ہے۔ آپ کے زائرین منظم رہتے ہیں۔',
    
    // Auth
    'auth.email': 'ای میل',
    'auth.password': 'پاس ورڈ',
    'auth.account': 'میرا اکاؤنٹ',
    'auth.signOut': 'سائن آؤٹ',
    'auth.loginDescription': 'اپنے ڈیش بورڈ تک رسائی کے لیے اپنی اسناد درج کریں',
    'auth.signupDescription': 'اپنے گروپس کا انتظام شروع کرنے کے لیے اکاؤنٹ بنائیں',
    
    // Dashboard
    'dashboard.title': 'ڈیش بورڈ',
    'dashboard.subtitle': 'آپ کے تمام تفویض کردہ گروپس کا جائزہ',
    'dashboard.searchPlaceholder': 'گروپس تلاش کریں...',
    'dashboard.groupName': 'گروپ کا نام',
    'dashboard.date': 'تاریخ',
    'dashboard.travelers': 'مسافر',
    'dashboard.booking': 'بکنگ',
    'dashboard.paperwork': 'کاغذات',
    'dashboard.messaging': 'پیغامات',
    'dashboard.progress': 'پیش رفت',
    'dashboard.open': 'کھولیں',
    'dashboard.openGroup': 'گروپ کھولیں',
    'dashboard.noGroups': 'کوئی گروپ نہیں ملا',
    'dashboard.bookingsConfirmed': 'بکنگز کی تصدیق',
    'dashboard.paperworkComplete': 'کاغذات مکمل',
    'dashboard.messagesSent': 'پیغامات بھیجے گئے',
    'dashboard.risk': 'خطرہ',
    'dashboard.totalGroups': 'کل گروپس',
    'dashboard.totalTravelers': 'کل مسافر',
    'dashboard.avgBooking': 'اوسط بکنگ',
    'dashboard.avgPaperwork': 'اوسط کاغذات',
    'dashboard.avgMessaging': 'اوسط پیغامات',
    'dashboard.refresh': 'ریفریش',
    'dashboard.retry': 'دوبارہ کوشش',
    'dashboard.sortBy': 'ترتیب',
    'dashboard.sortDateDesc': 'تاریخ (جدید)',
    'dashboard.sortDateAsc': 'تاریخ (پرانی)',
    'dashboard.sortCompletion': 'تکمیل',
    'dashboard.sortRisk': 'خطرے کی سطح',
    'dashboard.sortTravelers': 'مسافرین کی تعداد',
    'dashboard.filterBy': 'فلٹر',
    'dashboard.filterAll': 'تمام گروپس',
    'dashboard.filterComplete': 'مکمل',
    'dashboard.filterInProgress': 'جاری',
    'dashboard.filterAtRisk': 'خطرے میں',
    'dashboard.backToDashboard': 'ڈیش بورڈ پر واپس',
    'dashboard.groupDetail': 'گروپ کی تفصیل',
    'dashboard.groupDetailPlaceholder': 'مکمل گروپ مینجمنٹ انٹرفیس جلد آ رہا ہے...',
    // Group Detail
    'group.tabTravelers': 'مسافرین',
    'group.tabHotels': 'ہوٹل',
    'group.tabPaperwork': 'کاغذات',
    'group.tabMessaging': 'پیغامات',
    'group.tabExport': 'ایکسپورٹ',
    'group.name': 'نام',
    'group.passport': 'پاسپورٹ',
    'group.actions': 'اقدامات',
    'group.selected': 'منتخب',
    'group.confirmBookings': 'بکنگز کی تصدیق',
    'group.riskReasons': 'خطرے کی وجوہات',
    'group.available': 'دستیاب',
    'group.hotelAssignment': 'ہوٹل کی تفویض',
    'group.selectHotel': 'ہوٹل منتخب کریں',
    'group.left': 'باقی',
    'group.overbooking': 'اوور بکنگ',
    'group.assigned': 'تفویض',
    'group.pending': 'زیر التوا',
    'group.status': 'حیثیت',
    'group.overallProgress': 'مجموعی پیش رفت',
    'group.complete': 'مکمل',
    'group.inProgress': 'جاری',
    'group.incomplete': 'نامکمل',
    'group.filterByRisk': 'خطرے کے لحاظ سے',
    'group.highRisk': 'زیادہ خطرہ',
    'group.mediumRisk': 'درمیانہ خطرہ',
    'group.lowRisk': 'کم خطرہ',
    'group.markAllComplete': 'سب مکمل کریں',
    'group.selectTemplate': 'ٹیمپلیٹ منتخب کریں',
    'group.messagesSummary': 'پیغامات بھیجے گئے',
    'group.sent': 'بھیجا گیا',
    'group.template': 'ٹیمپلیٹ',
    'group.priority': 'ترجیح',
    'group.highPriority': 'اعلی',
    'group.mediumPriority': 'درمیانی',
    'group.lowPriority': 'کم',
    'group.openWhatsApp': 'واٹس ایپ',
    'group.markSent': 'بھیجا گیا',
    'group.markFailed': 'ناکام',
    'group.delivered': 'پہنچ گیا',
    'group.notSent': 'نہیں بھیجا',
    'group.failed': 'ناکام',
    'group.exportOptions': 'ایکسپورٹ کے اختیارات',
    'group.includeTravelers': 'مسافرین کی فہرست شامل کریں',
    'group.includeHotels': 'ہوٹل کی تفویض شامل کریں',
    'group.includePaperwork': 'کاغذات کی حیثیت شامل کریں',
    'group.includeMessaging': 'پیغامات کا خلاصہ شامل کریں',
    'group.includeAuditLog': 'آڈٹ لاگ شامل کریں',
    'group.previewReport': 'رپورٹ کا پیش نظارہ',
    'group.downloadReport': 'رپورٹ ڈاؤن لوڈ کریں',
    'group.reportPreview': 'رپورٹ کا پیش نظارہ',
    'group.clickPreview': 'رپورٹ دیکھنے کے لیے "پیش نظارہ" پر کلک کریں',
    'group.exportSuccess': 'رپورٹ کامیابی سے ڈاؤن لوڈ ہو گئی',
    'group.exportFailed': 'رپورٹ بنانے میں ناکامی',
    // Audit Log
    'audit.title': 'آڈٹ لاگ',
    'audit.subtitle': 'تمام سرگرمی اور تبدیلی کی تاریخ دیکھیں',
    'audit.search': 'سرچ',
    'audit.searchPlaceholder': 'عمل، وسیلہ، صارف سے تلاش کریں...',
    'audit.actionType': 'عمل کی قسم',
    'audit.allActions': 'تمام اقدامات',
    'audit.dateFrom': 'تاریخ سے',
    'audit.dateTo': 'تاریخ تک',
    'audit.selectDate': 'تاریخ منتخب کریں',
    'audit.clearFilters': 'فلٹرز صاف کریں',
    'audit.timestamp': 'وقت',
    'audit.agent': 'ایجنٹ',
    'audit.action': 'عمل',
    'audit.target': 'ہدف',
    'audit.notes': 'نوٹس',
    'audit.noLogs': 'کوئی آڈٹ لاگ نہیں ملا',
    'audit.showing': 'دکھا رہا ہے',
    'audit.of': 'کا',
    'audit.entries': 'اندراجات',
    'audit.exportSuccess': 'ایکسپورٹ کامیاب',
    'audit.exportFailed': 'ایکسپورٹ ناکام',
    'audit.logsExported': 'لاگز ایکسپورٹ',
    // Settings
    'settings.title': 'سیٹنگز',
    'settings.subtitle': 'اپنا اکاؤنٹ اور ترجیحات کا انتظام کریں',
    'settings.profile': 'پروفائل',
    'settings.profileDesc': 'اپنی ذاتی معلومات اپ ڈیٹ کریں',
    'settings.displayName': 'ظاہری نام',
    'settings.displayNamePlaceholder': 'آپ کا نام',
    'settings.changePassword': 'پاس ورڈ تبدیل کریں',
    'settings.changePasswordDesc': 'سیکیورٹی کے لیے اپنا پاس ورڈ اپ ڈیٹ کریں',
    'settings.currentPassword': 'موجودہ پاس ورڈ',
    'settings.newPassword': 'نیا پاس ورڈ',
    'settings.confirmPassword': 'پاس ورڈ کی تصدیق کریں',
    'settings.weak': 'کمزور',
    'settings.fair': 'معقول',
    'settings.good': 'اچھا',
    'settings.strong': 'مضبوط',
    'settings.passwordsMatch': 'پاس ورڈ ملتے ہیں',
    'settings.passwordsDontMatch': 'پاس ورڈ نہیں ملتے',
    'settings.invalidEmail': 'غلط ای میل پتہ',
    'settings.profileUpdated': 'پروفائل اپ ڈیٹ ہو گئی',
    'settings.profileUpdatedDesc': 'آپ کی پروفائل کامیابی سے اپ ڈیٹ ہو گئی ہے',
    'settings.passwordChanged': 'پاس ورڈ تبدیل ہو گیا',
    'settings.passwordChangedDesc': 'آپ کا پاس ورڈ کامیابی سے اپ ڈیٹ ہو گیا ہے',
    'settings.passwordMismatch': 'نئے پاس ورڈ نہیں ملتے',
    'settings.passwordTooWeak': 'پاس ورڈ بہت کمزور ہے',
    'settings.error': 'خرابی',
    'settings.updateFailed': 'اپ ڈیٹ کرنے میں ناکامی',
    'settings.passwordChangeFailed': 'پاس ورڈ تبدیل کرنے میں ناکامی',
    'settings.logoutFailed': 'لاگ آؤٹ کرنے میں ناکامی',
    'settings.saving': 'محفوظ ہو رہا ہے...',
    'settings.saveChanges': 'تبدیلیاں محفوظ کریں',
    'settings.updating': 'اپ ڈیٹ ہو رہا ہے...',
    'settings.updatePassword': 'پاس ورڈ اپ ڈیٹ کریں',
    'settings.loggingOut': 'لاگ آؤٹ ہو رہا ہے...',
    'settings.developerDebug': 'ڈویلپر ڈیبگ',
    'settings.environmentVars': 'ماحولیاتی متغیرات',
    'settings.sessionInfo': 'سیشن کی معلومات',
    'settings.sessionStatus': 'سیشن کی حیثیت',
    'settings.sessionExpired': 'سیشن ختم ہو گیا',
    'settings.sessionActive': 'فعال',
    'settings.minutesRemaining': 'منٹ باقی',
    'settings.remaining': 'باقی',
    'settings.userId': 'صارف کی شناخت',
    // Toast notifications
    'toast.travelerUpdated': 'مسافر اپ ڈیٹ',
    'toast.travelerUpdatedDesc': '{name} کو اپ ڈیٹ کیا گیا',
    'toast.travelerUpdatedDescGeneric': 'مسافر کی معلومات اپ ڈیٹ ہو گئیں',
    'toast.bookingConfirmed': 'بکنگ کی تصدیق',
    'toast.bookingConfirmedDesc': 'مسافر کی بکنگ کی تصدیق ہو گئی',
    'toast.bookingsConfirmedDesc': '{count} بکنگز کی تصدیق ہو گئی',
    'toast.paperworkComplete': 'کاغذات مکمل',
    'toast.paperworkCompleteDesc': '{name} کے کاغذات مکمل',
    'toast.paperworkCompleteDescGeneric': 'کاغذات کی حیثیت اپ ڈیٹ',
    'toast.messageSent': 'پیغام بھیجا گیا',
    'toast.messageSentDesc': '{name} کو پیغام بھیجا گیا',
    'toast.messageSentDescGeneric': 'پیغام کی حیثیت اپ ڈیٹ',
    'toast.groupStatusChanged': 'گروپ کی حیثیت تبدیل',
    'toast.groupStatusChangedDesc': '{name} کی حیثیت اپ ڈیٹ',
    'toast.groupStatusChangedDescGeneric': 'گروپ کی حیثیت اپ ڈیٹ',
    'toast.csvImported': 'CSV درآمد',
    'toast.csvImportedDesc': '{count} مسافرین کامیابی سے درآمد',
    'toast.csvImportedDescGeneric': 'مسافرین کامیابی سے درآمد',
    'toast.exportComplete': 'ایکسپورٹ مکمل',
    'toast.exportCompleteDesc': 'رپورٹ کامیابی سے ڈاؤن لوڈ',
    'toast.error': 'خرابی',
    'toast.errorDesc': 'ایک خرابی ہوئی',
    // CSV Upload
    'csv.title': 'مسافرین درآمد کریں',
    'csv.description': 'اس گروپ میں مسافرین شامل کرنے کے لیے CSV فائل اپ لوڈ کریں',
    'csv.dropHere': 'اپنی CSV فائل یہاں چھوڑیں',
    'csv.orClick': 'یا فائلیں براؤز کرنے کے لیے کلک کریں',
    'csv.downloadTemplate': 'ٹیمپلیٹ ڈاؤن لوڈ کریں',
    'csv.preview': 'درآمد کا پیش نظارہ',
    'csv.previewDescription': 'درآمد سے پہلے ڈیٹا کا جائزہ لیں',
    'csv.valid': 'درست قطاریں',
    'csv.invalid': 'غلط قطاریں',
    'csv.status': 'حیثیت',
    'csv.missingField': 'ضروری فیلڈ غائب: {field}',
    'csv.invalidPassport': 'غلط پاسپورٹ فارمیٹ',
    'csv.invalidRowsWarning': '{count} قطاروں میں خرابی ہے اور چھوڑ دی جائیں گی',
    'csv.cancel': 'منسوخ کریں',
    'csv.importing': 'درآمد ہو رہا ہے...',
    'csv.import': '{count} مسافرین درآمد کریں',
    // Demo walkthrough
    'demo.watchDemo': 'ڈیمو دیکھیں',
    'demo.demo': 'ڈیمو',
    'demo.step': 'قدم',
    'demo.previous': 'پچھلا',
    'demo.next': 'اگلا',
    'demo.finish': 'شروع کریں',
    'demo.welcome': 'UmrahOps میں خوش آمدید',
    'demo.welcomeDesc': 'ہم آپ کو دکھاتے ہیں کہ کیسے UmrahOps ہمارے لوکل فرسٹ، رازداری پر مرکوز طریقے سے عمرہ گروپ مینجمنٹ کو آسان بناتا ہے۔',
    'demo.heroSection': 'تیزی سے شروع کریں',
    'demo.heroSectionDesc': 'اپنا اکاؤنٹ بنانے کے لیے "مفت شروع کریں" پر کلک کریں۔ آپ کا تمام ڈیٹا آپ کے آلے پر رہتا ہے۔',
    'demo.features': 'بنیادی صلاحیتیں',
    'demo.featuresDesc': 'UmrahOps سمارٹ توثیق، واٹس ایپ انٹیگریشن، ناقابل تغیر آڈٹس، اور آف لائن فرسٹ فعالیت فراہم کرتا ہے۔',
    'demo.validation': 'سمارٹ توثیق',
    'demo.validationDesc': 'اوور بکنگز، پاسپورٹ تنازعات، اور گمشدہ معلومات کا خود بخود پتہ لگائیں اس سے پہلے کہ وہ مسائل بنیں۔',
    'demo.whatsapp': 'واٹس ایپ انٹیگریشن',
    'demo.whatsappDesc': 'ایک کلک سے زائرین کو پہلے سے بنے ہوئے پیغام ٹیمپلیٹس بھیجیں۔ ریئل ٹائم میں ڈیلیوری کی حیثیت ٹریک کریں۔',
    'demo.blueprint': 'انٹیگریشن بلیو پرنٹ',
    'demo.blueprintDesc': 'ہمارا پلگ اینڈ پلے فن تعمیر ایک .env کنفیگریشن فائل کے ذریعے آپ کے موجودہ سسٹمز سے جڑتا ہے۔',
    'demo.pipelines': 'طاقتور پائپ لائنز',
    'demo.pipelinesDesc': 'CSV درآمد سے PDF ایکسپورٹ تک، ہر پائپ لائن رفتار اور قابل اعتمادی کے لیے بہتر بنائی گئی ہے۔',
    'demo.getStarted': 'شروع کرنے کے لیے تیار؟',
    'demo.getStartedDesc': 'اپنا مفت اکاؤنٹ بنائیں اور اعتماد کے ساتھ اپنے عمرہ گروپس کا انتظام شروع کریں۔ کوئی ڈیٹا آپ کے آلے سے باہر نہیں جاتا۔',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('umrahops-language');
    return (saved as Language) || 'en';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('umrahops-language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  const isRTL = language === 'ur';

  useEffect(() => {
    document.documentElement.dir = isRTL ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
    
    if (isRTL) {
      document.body.style.fontFamily = "'Noto Nastaliq Urdu', serif";
    } else {
      document.body.style.fontFamily = '';
    }
  }, [language, isRTL]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
